// Code generated by "stringer -type=errGeneric -linecomment -output=stringers.go ."; DO NOT EDIT.

package lexorg

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ErrUninitialized-1]
	_ = x[ErrRewound-2]
	_ = x[ErrViewTooLarge-3]
}

const _errGeneric_name = "lexorg: need initializationlexorg: offset precedes retained stream byteslexorg: view longer than fill buffer"

var _errGeneric_index = [...]uint8{0, 27, 72, 108}

func (i errGeneric) String() string {
	i -= 1
	if i >= errGeneric(len(_errGeneric_index)-1) {
		return "errGeneric(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _errGeneric_name[_errGeneric_index[i]:_errGeneric_index[i+1]]
}
